#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --hotload true

sketchybar                                \
  --bar                                   \
    position=bottom                        \
    height=40                             \
    blur_radius=30                        \
    color=0x40000000                      \
    sticy=on \
                                          \
  --default                               \
    padding_left=0                        \
    padding_right=0                       \
    icon.font="Mononoki Nerd Font:Bold:17.0"  \
    label.font="Mononoki Nerd Font:Bold:14.0" \
    icon.color=0xffffffff                 \
    label.color=0xffffffff                \
    icon.padding_left=4                   \
    icon.padding_right=4                  \
    label.padding_left=4                  \
    label.padding_right=4                 \
    topmost=on

##### aerospace integration
sketchybar --add event aerospace_workspace_change

sketchybar --add item      workspace left                             \
           --subscribe     workspace aerospace_workspace_change       \
           --set workspace label=""                                   \
                           label.padding_right=16                     \
                           script="$PLUGIN_DIR/aerospace.sh"

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \

sketchybar --add item front_app left \
           --set front_app icon.drawing=on script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

